name: add_to_gallery_example
description: Demonstrates how to use the add_to_gallery plugin
publish_to: "none"

version: "1.0.0+1"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.4

dependencies:
  add_to_gallery:
    path: ../
  http: ^1.1.0
  image_picker: ^1.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.0.6
  device_info_plus: ^9.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/local-image-1.jpg
    - assets/local-image-2.jpg
